// Generated by scripts/generateTherapeuticSchema.ts.
// Phase 1 check-only artifact. Do not import this file at runtime yet.

import type { ClinicalProtocol, ProtocolComponentSlot, ProtocolFoodRule, ProtocolRuleTargets, ProtocolServiceRule, ProtocolSlotCandidate } from '../types.ts';

export const CLINICAL_PROTOCOLS: readonly ClinicalProtocol[] = [
  {
    "protocol_code": "CARDIAC",
    "protocol_name": "Cardiac Protection",
    "family": "cardiovascular",
    "default_texture": "regular",
    "default_meal_count": 6,
    "active": true
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "protocol_name": "General Hospital Baseline",
    "family": "general",
    "default_texture": "regular",
    "default_meal_count": 6,
    "active": true
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "protocol_name": "Renal Stage 4 Protection",
    "family": "renal",
    "default_texture": "regular",
    "default_meal_count": 6,
    "active": true
  },
  {
    "protocol_code": "T2DM",
    "protocol_name": "Type 2 Diabetes Glycemic Control",
    "family": "endocrine",
    "default_texture": "regular",
    "default_meal_count": 6,
    "active": true
  }
] as const;

export const PROTOCOL_RULE_TARGETS: readonly ProtocolRuleTargets[] = [
  {
    "protocol_code": "CARDIAC",
    "energy_formula": "BMR*activity*stress",
    "protein_g_per_kg_min": 0.8,
    "carb_pct_min": 0.4,
    "carb_pct_max": 0.5,
    "fat_pct_min": 0.28,
    "fat_pct_max": 0.33,
    "fiber_min_g": 30,
    "sodium_max_mg": 1500,
    "potassium_max_mg": null,
    "phosphorus_max_mg": null,
    "sugar_max_g": null,
    "gi_max": 60,
    "fluid_target_ml": "weightKg*30"
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "energy_formula": "BMR*activity*stress",
    "protein_g_per_kg_min": 0.8,
    "carb_pct_min": 0.45,
    "carb_pct_max": 0.55,
    "fat_pct_min": 0.25,
    "fat_pct_max": 0.35,
    "fiber_min_g": 25,
    "sodium_max_mg": 2000,
    "potassium_max_mg": null,
    "phosphorus_max_mg": null,
    "sugar_max_g": null,
    "gi_max": 60,
    "fluid_target_ml": "weightKg*30"
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "energy_formula": "BMR*activity*stress",
    "protein_g_per_kg_min": 0.6,
    "carb_pct_min": 0.48,
    "carb_pct_max": 0.56,
    "fat_pct_min": 0.28,
    "fat_pct_max": 0.35,
    "fiber_min_g": 20,
    "sodium_max_mg": 1500,
    "potassium_max_mg": 1800,
    "phosphorus_max_mg": 800,
    "sugar_max_g": null,
    "gi_max": 60,
    "fluid_target_ml": "manual_override"
  },
  {
    "protocol_code": "T2DM",
    "energy_formula": "BMR*activity*stress",
    "protein_g_per_kg_min": 0.8,
    "carb_pct_min": 0.35,
    "carb_pct_max": 0.45,
    "fat_pct_min": 0.3,
    "fat_pct_max": 0.35,
    "fiber_min_g": 30,
    "sodium_max_mg": 1800,
    "potassium_max_mg": null,
    "phosphorus_max_mg": null,
    "sugar_max_g": 25,
    "gi_max": 55,
    "fluid_target_ml": "weightKg*30"
  }
] as const;

export const PROTOCOL_FOOD_RULES: readonly ProtocolFoodRule[] = [
  {
    "protocol_code": "CARDIAC",
    "rule_type": "avoid",
    "food_tag": "high_saturated_fat",
    "priority": 10,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "CARDIAC",
    "rule_type": "avoid",
    "food_tag": "processed_meat",
    "priority": 9,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "CARDIAC",
    "rule_type": "avoid",
    "food_tag": "fried",
    "priority": 8,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "CARDIAC",
    "rule_type": "avoid",
    "food_tag": "trans_fat",
    "priority": 7,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "CARDIAC",
    "rule_type": "prefer",
    "food_tag": "omega_3",
    "priority": 10,
    "note": "Generated from requiredTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "rule_type": "avoid",
    "food_tag": "high_potassium",
    "priority": 10,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "rule_type": "avoid",
    "food_tag": "high_phosphorus",
    "priority": 9,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "rule_type": "avoid",
    "food_tag": "high_sodium",
    "priority": 8,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "rule_type": "avoid",
    "food_tag": "processed_meat",
    "priority": 7,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "T2DM",
    "rule_type": "avoid",
    "food_tag": "refined_sugar",
    "priority": 10,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "T2DM",
    "rule_type": "avoid",
    "food_tag": "high_gi",
    "priority": 9,
    "note": "Generated from forbiddenTags in clinicalProtocols.ts"
  },
  {
    "protocol_code": "T2DM",
    "rule_type": "prefer",
    "food_tag": "low_gi",
    "priority": 10,
    "note": "Generated from requiredTags in clinicalProtocols.ts"
  }
] as const;

export const PROTOCOL_SERVICE_RULES: readonly ProtocolServiceRule[] = [] as const;

export const PROTOCOL_COMPONENT_SLOTS: readonly ProtocolComponentSlot[] = [
  {
    "protocol_code": "CARDIAC",
    "meal_type": "breakfast",
    "slot_name": "wholegrain_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "breakfast",
    "slot_name": "lean_protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "breakfast",
    "slot_name": "vegetable_side",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "breakfast",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "dinner",
    "slot_name": "wholegrain_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "dinner",
    "slot_name": "lean_protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "dinner",
    "slot_name": "vegetable_side",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "dinner",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "lunch",
    "slot_name": "wholegrain_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "lunch",
    "slot_name": "lean_protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "lunch",
    "slot_name": "vegetable_side",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "CARDIAC",
    "meal_type": "lunch",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "breakfast",
    "slot_name": "starch_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "breakfast",
    "slot_name": "protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "breakfast",
    "slot_name": "veg_or_fruit_optional",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "breakfast",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "dinner",
    "slot_name": "starch_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "dinner",
    "slot_name": "protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "dinner",
    "slot_name": "veg_or_fruit_optional",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "dinner",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "lunch",
    "slot_name": "starch_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "lunch",
    "slot_name": "protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "lunch",
    "slot_name": "veg_or_fruit_optional",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "GENERAL_HOSPITAL",
    "meal_type": "lunch",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "breakfast",
    "slot_name": "renal_carb_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "breakfast",
    "slot_name": "renal_protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "breakfast",
    "slot_name": "renal_veg_side",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "breakfast",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "dinner",
    "slot_name": "renal_carb_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "dinner",
    "slot_name": "renal_protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "dinner",
    "slot_name": "renal_veg_side",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "dinner",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "lunch",
    "slot_name": "renal_carb_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "lunch",
    "slot_name": "renal_protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "lunch",
    "slot_name": "renal_veg_side",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "RENAL_STAGE_4",
    "meal_type": "lunch",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "breakfast",
    "slot_name": "controlled_carb_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "breakfast",
    "slot_name": "protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "breakfast",
    "slot_name": "fiber_side_optional",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "breakfast",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "dinner",
    "slot_name": "controlled_carb_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "dinner",
    "slot_name": "protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "dinner",
    "slot_name": "fiber_side_optional",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "dinner",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "lunch",
    "slot_name": "controlled_carb_base",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 1
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "lunch",
    "slot_name": "protein_primary",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 2
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "lunch",
    "slot_name": "fiber_side_optional",
    "required": false,
    "min_items": 0,
    "max_items": 1,
    "slot_order": 3
  },
  {
    "protocol_code": "T2DM",
    "meal_type": "lunch",
    "slot_name": "beverage",
    "required": true,
    "min_items": 1,
    "max_items": 1,
    "slot_order": 4
  }
] as const;

export const PROTOCOL_SLOT_CANDIDATES: readonly ProtocolSlotCandidate[] = [] as const;

// FOODS are intentionally not generated in Phase 1; food catalog authority is separate from diagnosis protocols.
export { FOODS } from './therapeuticSchema.ts';
