import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ProtocolSlotCandidate } from '../types.ts';
import type { ProtocolSlotCandidateSource } from './exportProtocolSlotCandidates.ts';

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_PATH = path.join(ROOT_DIR, 'data', 'protocol-slot-candidates.source.json');
const OUTPUT_PATH = path.join(ROOT_DIR, 'config', 'protocolSlotCandidates.generated.ts');

function readSource(): ProtocolSlotCandidateSource[] {
  if (!fs.existsSync(SOURCE_PATH)) {
    throw new Error(
      `Missing ${path.relative(ROOT_DIR, SOURCE_PATH)}. Run scripts/exportProtocolSlotCandidates.ts first.`,
    );
  }

  return JSON.parse(fs.readFileSync(SOURCE_PATH, 'utf8')) as ProtocolSlotCandidateSource[];
}

function projectRuntimeCandidates(source: ProtocolSlotCandidateSource[]): ProtocolSlotCandidate[] {
  return [...source]
    .sort((a, b) => a.legacyOrder - b.legacyOrder)
    .map((candidate) => ({
      protocol_code: candidate.protocolCode,
      meal_type: candidate.mealType,
      slot_name: candidate.slotName,
      food_id: candidate.foodId,
      priority: candidate.priority,
    }));
}

function renderCandidate(candidate: ProtocolSlotCandidate): string {
  return `  { protocol_code: ${JSON.stringify(candidate.protocol_code)}, meal_type: ${JSON.stringify(candidate.meal_type)}, slot_name: ${JSON.stringify(candidate.slot_name)}, food_id: ${JSON.stringify(candidate.food_id)}, priority: ${candidate.priority} },`;
}

function renderArtifact(candidates: ProtocolSlotCandidate[]): string {
  return [
    '// Generated by scripts/generateProtocolSlotCandidates.ts.',
    '// Phase 2 check-only artifact. Do not import this file at runtime yet.',
    '',
    "import type { ProtocolSlotCandidate } from '../types.ts';",
    '',
    'export const PROTOCOL_SLOT_CANDIDATES: readonly ProtocolSlotCandidate[] = [',
    ...candidates.map(renderCandidate),
    '] as const;',
    '',
  ].join('\n');
}

function main(): void {
  const source = readSource();
  const candidates = projectRuntimeCandidates(source);
  fs.writeFileSync(OUTPUT_PATH, renderArtifact(candidates), 'utf8');

  console.log(`Generated ${candidates.length} protocol slot candidates.`);
  console.log(`Wrote ${path.relative(ROOT_DIR, OUTPUT_PATH)}`);
}

main();
